name: CD Workflow

on:
  push:
    branches:
      - main

env:
  RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
  IMAGE_NAME: registry.render.com/${{ secrets.RENDER_APP_NAME }}/web

jobs:
  cd:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Render login
        run: render container:login

      - name: Build and push docker image
        run: |
          docker build -t ${{env.IMAGE_NAME}} --build-arg BASE_API_URL=${{secrets.BASE_API_URL}} .
          docker push ${{env.IMAGE_NAME}}

      - name: Deploy to Render
        run: render container:release web -a ${{ secrets.RENDER_APP_NAME }}
